import { supabase } from "./supabase";

/**
 * Fetch wallpapers generated by the current user with pagination.
 */
export async function getUserWallpapers(userId: string, limit = 12, offset = 0) {
  const { data, error } = await supabase
    .from("wallpapers")
    .select("id, prompt, image_url, created_at")
    .eq("user_id", userId)
    .order("created_at", { ascending: false })
    .range(offset, offset + limit - 1);

  if (error) throw error;
  return data ?? [];
}

/**
 * Delete a wallpaper record by its ID.
 * Only deletes if the row belongs to the current user (enforced by RLS).
 */
export async function deleteWallpaper(wallpaperId: string) {
  const { error } = await supabase.from("wallpapers").delete().eq("id", wallpaperId);

  if (error) throw error;
}
