import { supabase } from './supabase';

/**
 * Fetch all wallpapers generated by the current user,
 * ordered by most recent first.
 */
export async function getUserWallpapers(userId: string) {
  const { data, error } = await supabase
    .from('wallpapers')
    .select('id, prompt, image_url, created_at')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) throw error;
  return data ?? [];
}

/**
 * Delete a wallpaper record by its ID.
 * Only deletes if the row belongs to the current user (enforced by RLS).
 */
export async function deleteWallpaper(wallpaperId: string) {
  const { error } = await supabase
    .from('wallpapers')
    .delete()
    .eq('id', wallpaperId);

  if (error) throw error;
}
